### ISSUE TITLE
pymsfilereader for mac? 

### ISSUE THREAD

**Issue by viviantra** [frallain/MSFileReader_Python_bindings#6]
Hi, 

Thermo had developed assembly to replace MSFileReader. 
 It supposed to interface better. 
https://planetorbitrap.com/rawfilereader
I am using a Mac, so I cannot install MSFileReader anyway.   There are four .dll files in rawfilereader:  

ThermoFisher.CommonCore.Data.dll
ThermoFisher.CommonCore.MassPrecisionEstimator.dll
ThermoFisher.CommonCore.RawFileReader.dll
ThermoFisher.CommonCore.BackgroundSubtraction.dll

How do I make it work?

Thanks, 

Vivian

**Comment by rexdwyer** [comment]
HI Vivian,
There is a package called RawQuant that interfaces with the new library: pip install RawQuant.  I believe it will work with a mac.
I have been using it since yesterday.  I'm really grateful to François for his wrappers, but the underlying library is outdated and buggy.  Have you contacted Jim Shofstahl from Thermo at the address on page you linked to?  He's being quite helpful.
Rex

**Comment by chrishuges** [comment]
Just to chime in here if you decide to go the RawQuant route: I would actually recommend you use RawTools (https://github.com/kevinkovalchik/RawTools) instead of RawQuant. Although RawQuant does interface with this Python package, we are no longer supporting it. RawTools remains fully supported, has all the functionality and more of RawQuant, and even has a GUI if you want it. RawTools is built on the new ThermoRawFileReader library and works on Linux, Mac, and Windows. Feel free to post an issue or a feature request if you have troubles or we are missing a feature you would like to see!

**Comment by viviantra** [comment]
Hi, Rex and Chris, 

Thank you so much for your information!  I managed to get peak extraction from an R library called rawDiag.  So I am not going to spend time on RawTools for now.  However, I will definitely keep it in mind.   
Yes, I contacted Jim.  He was very helpful! 

Vivian
